---
name: cd

"on":
  workflow_dispatch:
  push:
    branches:
      - flyio

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: deploy filmbot
    runs-on: ubuntu-latest
    environment:
      name: flyio
    steps:
      - name: checkout project
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - name: install cosign
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
      - name: verify filmbot image
        run: |
          cosign verify \
             --certificate-identity \
             'https://github.com/andros21/filmbot/.github/workflows/ci.yml@refs/heads/master' \
             --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
             "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" | jq .
      - name: flyio setup
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: flyio deploy
        run: |
          flyctl deploy --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
