---
name: ci

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
      - fly.toml
      - '.gitignore'
      - '.github/workflows/*'
      - '.github/dependabot.yaml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
      - fly.toml
      - '.gitignore'
      - '.github/workflows/*'
      - '.github/dependabot.yaml'

permissions:
  contents: read
  id-token: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: build filmbot
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: rust stable latest
        id: rust
        run: |
          latest="$(curl -sL https://api.github.com/repos/rust-lang/rust/releases/latest | jq -r .tag_name)"
          echo "rust stable latest: ${latest}"
          echo "stable_latest=${latest}" >> "$GITHUB_OUTPUT"
      - name: check cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        id: cache
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            target/
          key: ${{ runner.os }}-rust-${{ steps.rust.outputs.stable_latest }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
      - name: cargo fmt
        run: |
          cargo fmt -- --check --verbose
      - name: cargo clippy
        run: |
          cargo clippy --locked --workspace
      - name: build filmbot
        run: |
          cargo build --release --locked
      - name: install cosign
        uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19
      - name: verify base images
        run: |
          cosign dockerfile verify \
            --certificate-identity \
            'https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main' \
            --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
            Dockerfile | jq .
      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
      - name: login ghcr.io
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: build filmbot (devel)
        id: docker
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ steps.buildx.outputs.name }}
          sbom: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          provenance: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          load: ${{ github.event_name == 'pull_request' }}
      - name: smoke test
        run: |
          set -x
          # only ensure runtime deps are ok
          docker run --rm \
            "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.docker.outputs.digest }}" &> filmbot.log || true
          cat filmbot.log
          grep --quiet --fixed-strings "TELOXIDE_TOKEN" filmbot.log
      - name: cosign filmbot
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          cosign sign -y "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.docker.outputs.digest }}"
      - name: install crane
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c
      - name: tag filmbot (latest)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          crane tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel" latest
