---
name: ci

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
      - fly.toml
      - '.gitignore'
      - '.github/workflows/*'
      - '.github/dependabot.yaml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
      - fly.toml
      - '.gitignore'
      - '.github/workflows/*'
      - '.github/dependabot.yaml'

permissions:
  contents: read
  id-token: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: build filmbot
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: rust stable latest
        id: rust
        run: |
          latest="$(curl -sL https://api.github.com/repos/rust-lang/rust/releases/latest | jq -r .tag_name)"
          echo "rust stable latest: ${latest}"
          echo "stable_latest=${latest}" >> "$GITHUB_OUTPUT"
      - name: check cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84
        id: cache
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            target/
          key: ${{ runner.os }}-rust-${{ steps.rust.outputs.stable_latest }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
      - name: cargo fmt
        run: |
          cargo fmt -- --check --verbose
      - name: cargo clippy
        run: |
          cargo clippy --locked --workspace
      - name: build filmbot
        run: |
          cargo build --release --locked
      - name: install cosign
        uses: sigstore/cosign-installer@9614fae9e5c5eddabb09f90a270fcb487c9f7149
      - name: verify base images
        run: |
          cosign dockerfile verify \
            --certificate-identity \
            'https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main' \
            --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
            Dockerfile | jq .
      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
      - name: login ghcr.io
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker metadata
        id: meta
        uses: docker/metadata-action@9dc751fe249ad99385a2583ee0d084c400eee04e
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: build filmbot (devel)
        id: docker
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: .
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ steps.buildx.outputs.name }}
          sbom: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          provenance: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          load: ${{ github.event_name == 'pull_request' }}
      - name: smoke test
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          set -x
          # only ensure runtime deps are ok
          docker run --rm \
            "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.docker.outputs.digest }}" &> filmbot.log || true
          cat filmbot.log
          grep --quiet --fixed-strings "TELOXIDE_TOKEN" filmbot.log
      - name: smoke test
        if: github.event_name == 'pull_request'
        run: |
          set -x
          # only ensure runtime deps are ok
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel &> filmbot.log || true
          cat filmbot.log
          grep --quiet --fixed-strings "TELOXIDE_TOKEN" filmbot.log
      - name: cosign filmbot
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          cosign sign -y "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.docker.outputs.digest }}"
      - name: install crane
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c
      - name: tag filmbot (latest)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          crane tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel" latest
