---
name: ci

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
      - fly.toml
      - '.gitignore'
      - '.github/workflows/*'
      - '.github/dependabot.yaml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
      - fly.toml
      - '.gitignore'
      - '.github/workflows/*'
      - '.github/dependabot.yaml'

permissions:
  contents: read
  id-token: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: build filmbot
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - name: rust stable latest
        id: rust
        run: |
          latest="$(curl -sL https://api.github.com/repos/rust-lang/rust/releases/latest | jq -r .tag_name)"
          echo "rust stable latest: ${latest}"
          echo "stable_latest=${latest}" >> "$GITHUB_OUTPUT"
          used="$(cargo --version | awk '{print $2}')"
          echo "rust stable used: ${used}"
          echo "stable_used=${used}" >> "$GITHUB_OUTPUT"
      - name: check cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        id: cache
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            target/
          key: ${{ runner.os }}-rust-${{ steps.rust.outputs.stable_latest }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
      - name: update toolchain
        if: steps.rust.outputs.stable_latest != steps.rust.outputs.stable_used
        run: |
          rustup update stable
      - name: cargo fmt
        run: |
          cargo fmt -- --check --verbose
      - name: cargo clippy
        run: |
          cargo clippy --locked --workspace
      - name: build filmbot
        run: |
          cargo build --release --locked
      - name: install cosign
        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4
      - name: verify base images
        run: |
          cosign dockerfile verify \
            --certificate-identity \
            'https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main' \
            --certificate-oidc-issuer 'https://token.actions.githubusercontent.com' \
            Dockerfile | jq .
      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb
      - name: login ghcr.io
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: build filmbot (devel)
        id: docker
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ steps.buildx.outputs.name }}
          sbom: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          provenance: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          load: ${{ github.event_name == 'pull_request' }}
      - name: smoke test
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          set -x
          # only ensure runtime deps are ok
          docker run --rm \
            "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.docker.outputs.digest }}" &> filmbot.log || true
          cat filmbot.log
          grep --quiet --fixed-strings "TELOXIDE_TOKEN" filmbot.log
      - name: smoke test
        if: github.event_name == 'pull_request'
        run: |
          set -x
          # only ensure runtime deps are ok
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel &> filmbot.log || true
          cat filmbot.log
          grep --quiet --fixed-strings "TELOXIDE_TOKEN" filmbot.log
      - name: cosign filmbot
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          cosign sign -y "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.docker.outputs.digest }}"
      - name: install crane
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c
      - name: tag filmbot (latest)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          crane tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel" latest
